	CREATE TABLE IF NOT EXISTS `inventario_db`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `precio` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  `cantidad` INT NOT NULL DEFAULT 0,
  `tipo` VARCHAR(50) NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
